# Generated by Django 5.1.1 on 2024-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('date_requested', models.CharField(default='', max_length=50)),
                ('time_requested', models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('1:00', '1:00'), ('2:00', '2:00'), ('3:00', '3:00'), ('4:00', '4:00'), ('5:00', '5:00')], default='', max_length=50)),
                ('service_type', models.CharField(choices=[('Hair Styling', 'Hair Styling'), ('Face Mask', 'Face Mask'), ('Shaving', 'Shaving'), ('Beard Trimming', 'Beard Trimming'), ('Hair Wash', 'Hair Wash')], default='', max_length=50)),
                ('barber_name', models.CharField(choices=[('Kamji', 'Kamji'), ('Stephen', 'Stephen'), ('Helen', 'Helen')], default='', max_length=50)),
            ],
        ),
    ]
