# Generated by Django 5.1.1 on 2024-10-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kchairskincarev2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='barber_name',
            field=models.CharField(choices=[('Kamji', 'Kamji'), ('Joel', 'Joel'), ('Katiria', 'Katiria')], default='', max_length=50),
        ),
    ]
