# Generated by Django 5.1.1 on 2024-10-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kchairskincarev2_app', '0002_alter_appointmentrequest_barber_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(max_length=80)),
                ('question', models.TextField(max_length=200)),
            ],
        ),
    ]
